### ISSUE TITLE
Re-generate Atlas and game.png for 1.0.4

### ISSUE THREAD

**Issue by AdityaMH** [AdityaMH/Pix5-Tileset#3]
Since I don't have PC to generate atlas and game.png
I need help for everyone who can generate atlas and png from pc.

How to generate:
 - Update to lastest version.
 - Delete "game.atlas" and "game.png" from Pix5 Tileset folder
 - Just open Unciv normally
 - Fork this repo
 - Find file "game.atlas" and "game.png" from Pix5 Tileset folder, upload it to your fork and Pull Request.

Or other alternative is just Upload zipped atlas and png to this issue.
I will PR myself

**Comment by will-ca** [comment]
The PRs I sent in included atlases, BTW. Check the file commit histories/most recent commits.

**Comment by AdityaMH** [comment]
Um i know that, but i'm add re-new image tiles.
so your atlas not for 1.0.4, but still 1.0.3 version.

Still many tile need to be edited because some tile from 5hex (sorry ravignir) and pixel and file size from 5hex is more larger than pix5.

Maybe that reason, map editor can be bugged if you using pix5

**Comment by AdityaMH** [comment]
Another reason why i really hate this.
I'm really need atlas and.png for this update (a7832e7). *Override is best option.
![Bug](https://cdn.discordapp.com/attachments/588357826758574106/924424208560312400/IMG_20211226_051114.jpg)
![Bug](https://cdn.discordapp.com/attachments/588357826758574106/924424450726842368/IMG_20211226_051233.jpg)

**Comment by will-ca** [comment]
@AdityaMH Yeah. I'll submit a patch for tileset fallback either tonight or tomorrow morning.
